export const ADMIN_ENDPOINTS="http://localhost:5000/admin"
export const USER_ENDPOINTS="http://localhost:5000/user"
// export const AUTH_ENDPOINTS="http://localhost:5000/api/auth"
export const CONTACT_ENDPOINTS="http://localhost:5000/api"
export const BASE_URL="http://localhost:3000"

// export const ADMIN_ENDPOINTS="https://spt-classes-backend-taha.onrender.com/admin"
// export const USER_ENDPOINTS="https://spt-classes-backend-taha.onrender.com/user"
export const AUTH_ENDPOINTS="https://spt-classes-backend-taha.onrender.com/api/auth"
// export const CONTACT_ENDPOINTS="https://spt-classes-backend-taha.onrender.com/api"